# Generated by Django 4.1.2 on 2023-03-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='title')),
                ('slug', models.CharField(blank=True, max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menues',
            },
        ),
        migrations.CreateModel(
            name='TreeMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('path', models.CharField(blank=True, max_length=1000, verbose_name='path')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treemenu.treemenu', to_field='slug', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menue Items',
            },
        ),
    ]
