# Generated by Django 4.1.2 on 2023-03-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menues',
            },
        ),
        migrations.CreateModel(
            name='TreeMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='slug')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tree_menu.treemenu', to_field='slug', verbose_name='Parent menu')),
                ('parent_sub_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree_menu.treemenuitem', to_field='slug', verbose_name='Parent sub-menu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menue Items',
            },
        ),
    ]
