# Generated by Django 4.1.2 on 2023-03-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenuitem',
            name='parent_sub_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tree_menu.treemenuitem', to_field='slug', verbose_name='Parent sub-menu'),
        ),
    ]
